Real Fix #4 🤨
Blobanium/MCBrowser pull request #5
Opened 2023-11-08 21:51 UTC by HiWord9

The problem on calling BrowserScreen, not on which request u give to it

2023-11-08 22:47 UTC, HiWord9 commented
also added support for instant download resource packs on modrinth.com/resourcepack same as modrinth.com/mod in [c332fa6](https://github.com/Blobanium/MCBrowser/pull/5/commits/c332fa6f4bf3528c2ac0edbe26abedd4fccc0e77)

2023-11-09 01:25 UTC, Blobanium requested changes

2023-11-09 01:25 UTC, Blobanium commented on src/main/resources/assets/mcbrowser/lang/en_us.json
Try not to duplicate translations. I can see some entries on lines 12, 14, 16 and 17 that can be reused on 6, 8, 10 and 11 respectfully. This is so translations from previous versions can still be good in future versions (if you can understand what i mean im not good at english xd). It also cuts down on mod size by a marginal amount as well.

2023-11-09 21:32 UTC, Blobanium approved these changes
Changes look good! Here's your stamp of approval.

2023-11-09 21:33 UTC, Blobanium commented
Anything else you might want to add before i merge this PR by any chance?

2023-11-09 22:05 UTC, HiWord9 commented
I I'd like to add something else I will make new PR lol

2023-11-09 22:45 UTC, merged